### PR TITLE
Supports merging cell borders

### PR DESCRIPTION
**Pull request by FutoTan**
Dear justkawal,
I also found that the borders will not be applied afther merging cells. So, I invested some time into fixing that. 
Now, you are able to set style of a group of merging cells by `setMergedCellStyle(CellIndex start, CellStyle mergedCellStyle)`.

hopes that helps!

## Before
Before
## After
After

### CODE REVIEW

**Comment by FauconSpartiate** [comment]
Good job 👍
Could you also add some test cases to make sure it doesn't break again?

**Comment by FauconSpartiate** [comment]
This is just an example. The tests in the `test` folder get executed at every release and ensure that features work as expected. You give it some input and analyse the output to look if it's correct.

Just look at the tests that are already present, it's relatively straight forward.

**Comment by FutoTan** [comment]
> This is just an example. The tests in the `test` folder get executed at every release and ensure that features work as expected. You give it some input and analyse the output to look if it's correct.
> 
> Just look at the tests that are already present, it's relatively straight forward.

Like this?

https://github.com/justkawal/excel/blob/014c700e1188bcfc8dcee41c1468b350b85da5d3/test/excel_test.dart#L357-L452

In addition, I found that my previous implementation method was too cumbersome and made many code modifications. So I revoked the commit and reimplemented it by coding the `setMergedCellStyle(CellIndex start, CellStyle mergedCellStyle)` method. It is much more streamlined than before, and I believe that the probability of breaking should be much lower.

**Review by FauconSpartiate — DISMISSED** [review]
LGTM

**Comment by FauconSpartiate** [comment]
@justkawal

**Review by justkawal — APPROVED** [review]
LGTM

**Review by FauconSpartiate — APPROVED** [review]

**Comment by yogithesymbian** [comment]
> setMergedCellStyle

what version ? 
```
The method 'setMergedCellStyle' isn't defined for the type 'Sheet'.
Try correcting the name to the name of an existing method, or defining a method named 'setMergedCellStyle'
```
i use `excel: ^2.1.0` 
diagonal border is work , but for bottom is not work , the result always like on `before`.

**Comment by FutoTan** [comment]
> > setMergedCellStyle
> 
> what version ?
> 
> ```
> The method 'setMergedCellStyle' isn't defined for the type 'Sheet'.
> Try correcting the name to the name of an existing method, or defining a method named 'setMergedCellStyle'
> ```
> 
> i use `excel: ^2.1.0` diagonal border is work , but for bottom is not work , the result always like on `before`.
> 
> ```
> sheet.merge(
>             CellIndex.indexByString("$columnName$indexStartHeaderData"),
>             CellIndex.indexByString("$columnName${indexStartHeaderData + 1}"),
>             customValue: rowLabel[i - 1],
>           );
>           sheet.setMergedCellStyle() // not defined
> 
> // excel.sheets.
>           // print('header column : $columnName$indexStartHeaderData');
>           // var cell = sheet.cell(CellIndex.indexByString(
>           //     "$columnName${indexStartHeaderData - 1}"));
>           // cell.cellStyle = cellHeaderStyle.copyWith(
>           //   horizontalAlignVal: HorizontalAlign.Center,
>           //   verticalAlignVal: VerticalAlign.Center,
>           // );
> 
> excel.updateCell(
>             sheetName,
>             CellIndex.indexByString("$columnName$indexStartHeaderData"),
>             rowLabel[i - 1],
>             cellStyle: CellStyle(
>               fontSize: 25,
>               topBorder: border,
>               bottomBorder: border, // result like `before` the border is gone
>               leftBorder: border,  // also not full result like `before` the border is gone
>               rightBorder: border, // also not full result like `before` the border is gone
>               diagonalBorder: border, // work
>               diagonalBorderDown: true, // work
>             ),
>           );
> ```

Dear @yogithesymbian, the owner of this repo plans to merge this RP into the 3.0.0, which is not available on pub.dev yet.
But you could use the dev branch just like this:
````yaml
excel:
  git:
    url: git@github.com:justkawal/excel.git
    ref: bump-3.0.0
````

**Comment by yogithesymbian** [comment]
> setMergedCellStyle(CellIndex start, CellStyle mergedCellStyle)

oke thankyou bro 🚀

**Comment by FauconSpartiate** [comment]
@yogithesymbian `3.0.0` has been released on pub.dev

**Pull request merged**
