### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by FauconSpartiate**
- Add some missing functions for controlling column width and row height
- Avoid using abreviations, mainly col instead of column
- Change CHANGELOG.md to adhere to [Keep A Changelog](https://keepachangelog.com/en/1.1.0/)
- Clean up README.md and remove old information
- Clean up some comments
- Apply formatting rules

### Breaking Changes

- Renamed `getColAutoFits()` to `getColumnAutoFits()`, and changed return type to `Map<int, bool>` in `Sheet`
- Renamed `getColWidths()` to `getColumnWidths()`, and changed return type to `Map<int, double>` in `Sheet`
- Renamed `getColAutoFit()` to `getColumnAutoFit()` in `Sheet`
- Renamed `getColWidth()` to `getColumnWidth()` in `Sheet`
- Renamed `setColAutoFit()` to `setColumnAutoFit()` in `Sheet`
- Renamed `setColWidth()` to `setColumnWidth()` in `Sheet`

### CODE REVIEW

**Comment by FauconSpartiate** [comment]
@justkawal Review needed

**Review by justkawal — COMMENTED** [review]
Great Work.. LGTM

Can you add a bit documentation about breaking changes like variable or optional parameter renames which would break others code may be!!...

**Comment by FauconSpartiate** [comment]
Breaking changes are already described in the changelog of #255, but I can also paste them in this issue.

Should we also have them in the README?

**Comment by FauconSpartiate** [comment]
### Breaking Changes

- Renamed getColAutoFits() to getColumnAutoFits(), and changed return type to Map<int, bool> in Sheet
- Renamed getColWidths() to getColumnWidths(), and changed return type to Map<int, double> in Sheet
- Renamed getColAutoFit() to getColumnAutoFit() in Sheet
- Renamed getColWidth() to getColumnWidth() in Sheet
- Renamed setColAutoFit() to setColumnAutoFit() in Sheet
- Renamed setColWidth() to setColumnWidth() in Sheet

**Comment by FauconSpartiate** [comment]
@justkawal Review needed

**Review by justkawal — APPROVED** [review]
LGTM

**Pull request merged**
