### PR TITLE
Supports merging cell borders

### PR DESCRIPTION
**Pull request by FutoTan**
Dear justkawal,
I also found that the borders will not be applied afther merging cells. So, I invested some time into fixing that. 
hopes that helps!

## Before
Before
## After
After

### CODE REVIEW

**Comment by FutoTan** [comment]
My bad, remove() is not implemented in low version of xml. Although it work fine on the example.

**Comment by FauconSpartiate** [comment]
@FutoTan What do you mean with "it os not implemented in low version of XML"?
Of needed, the dependencies can be tightened...

**Comment by FauconSpartiate** [comment]
(PR's get updated if you commit to the branch, there was no need to create a new one)

**Comment by FutoTan** [comment]
> @FutoTan What do you mean with "it is not implemented in low version of XML"? Of needed, the dependencies can be tightened...

I don't know whether what I said is correct. When I added this branch to my own project's dependencies, it failed to build and raised the error `method 'remove' is not defined for the class' XmlElement'`.
And for RPs, sorry for that, I did not know this feature before.

**Pull request closed without merging**
