### PR TITLE
Bump to 2.1.0

### PR DESCRIPTION
**Pull request by FauconSpartiate**
### Improved
- Add border functionality
### Fixed
- Fix Header and Footer with special characters
- Fix sheet.merge()

### CODE REVIEW

**Comment by FauconSpartiate** [comment]
This is because there is a new feature being introduced, and following the MAJOR.MINOR.PATCH scheme, `2.1.0` should be used.
Semantic versioning recommends that the last number should only be used for patches and minor fixes (https://semver.org/).
But if you want, we can change it to `2.0.5`, it's not like this changes anything... 😅

**Review by justkawal — DISMISSED** [review]
LGTM

**Comment by FauconSpartiate** [comment]
@justkawal how are 3 reviewers supposed to approve this when there are only 2, minus me as I'm the author?

**Comment by amigne** [comment]
@FauconSpartiate: Wouldn't you also update README.md, from
```yaml
dependencies:
  excel: 2.0.4
```
to
```yaml
dependencies:
  excel: 2.1.0
```

The user would then be invited to install the last release.

**Review by amigne — APPROVED** [review]
LGTM.

Thank you.

**Comment by justkawal** [comment]
> @justkawal how are 3 reviewers supposed to approve this when there are only 2, minus me as I'm the author?

It was set to 2 and was waiting for @amigne to accept the invitation.

**Review by justkawal — APPROVED** [review]
LGTM

**Pull request merged**
