### PR TITLE
Custom column width & autofit

### PR DESCRIPTION
**Pull request by f978gDDfsa**
Dear justkawal,
I added the new functions: set column width and autofit (not perfect, because it's very difficult to calculate). 
Please, check this pull request.
Thank you in advance!

### CODE REVIEW

**Comment by justkawal** [comment]
@f978gDDfsa 
The changes looks pretty well, 
Just to make sure, Have you considered the merging of rows and columns and then applying the column and row resizing, because this is the main thing which is tricky to resolve and I was thinking on it before coming to an optimised approach

You have done a pretty well and I appreciate that,

Please tell me that have you considered the merging and spanning case scenario or not ?

Otherwise I'll have a look into it.

**Comment by f978gDDfsa** [comment]
Unfortunately, I didn't test this case.
I will check it too.

**Comment by justkawal** [comment]
@f978gDDfsa 
Thanks for improving open source community, I'm humbled by your help.

**Comment by wterrill** [comment]
This is great!  I'm looking forward to having this in the official version.  thanks @f978gDDfsa !!!

**Comment by justkawal** [comment]
@f978gDDfsa Thanks for pull-request, The looks good and works as expected, 

There is one little thing which might break the code, i.e. Array Index out of bound exception on getting the autoWidth and widthDouble from the array.

I'll look into it,

**Comment by dsyrstad** [comment]
@justkawal Can you publish to pub.dev - and perhaps make 2.0.0-null-safety the current release?

**Pull request merged**
