### PR TITLE
Environment update

### PR DESCRIPTION
**Pull request by adarsh-kh4u**

### CODE REVIEW

**Comment by justkawal** [comment]
@adarsh-kh4u Will review after conflicts are resolved.

**Comment by FauconSpartiate** [comment]
What is this change actually for? This only restricts compatibility with people's apps that rely on older versions...
Is there a reasoning behind changing the dart environment version?

**Comment by justkawal** [comment]
> What is this change actually for? This only restricts compatibility with people's apps that rely on older versions...
> Is there a reasoning behind changing the dart environment version? @adarsh-kh4u

Agreed 💯, @adarsh-kh4u Can you please give out a reason for this change ?

**Comment by FauconSpartiate** [comment]
As there is no explanation for this PR and it's counterproductive, I'll go ahead and close it.

**Pull request closed without merging**
