### PR TITLE
Fix background color parsing

### LINKED ISSUE #234: backgroundColorHex issue
Apparently when import .xlsx file of var excel = Excel.decodeBytes(bytes); are not loading the background colors that already exist, so after you saving the file, the background colors are broak in one single color.

### PR DESCRIPTION
**Pull request by FauconSpartiate**
Fixes #234
A typo made the background color parsing return always null

### CODE REVIEW

**Review by justkawal — APPROVED** [review]
Eagle's Eye @FauconSpartiate 
Good catch

Approved LGTM

**Comment by Daybayzayd** [comment]
Is this fix published in the last pub.dev version ?
Because i have always null when i try and i have the latest version installed.

**Comment by FauconSpartiate** [comment]
@Daybayzayd nope, hasn't been released, should be done someday, indeed 😅

**Comment by Daybayzayd** [comment]
@FauconSpartiate No problem, i discovered the functionnality allowing me to add a github repository as a dependency in my pubspec.yaml thanks to this problem. :D

**Comment by justkawal** [comment]
Released yesterday I guess…. Haha

Try the version:
```yaml
excel: ^4.0.0
```

**Comment by justkawal** [comment]
Sorry for the delay.

**Pull request merged**
