### PR TITLE
changed archive version to 3.6.1

### PR DESCRIPTION
**Pull request by Tom-ne**
bumped archive version to 3.6.1 for compatibility with newest flutter version

### CODE REVIEW

**Comment by FauconSpartiate** [comment]
@Tom-ne Why do you need this explicit upgrade? The 3.6.1 version is already included in the previous constraint.

https://dart.dev/tools/pub/dependencies#caret-syntax

**Comment by Tom-ne** [comment]
I need this explicit upgrade because when trying the run a project with the packages using the latest flutter version, there is an error.
```
/C:/Users/yyyy/AppData/Local/Pub/Cache/hosted/pub.dev/archive-3.4.9/lib/src/bzip2/bzip2.dart:5:7: Error: Method not found: 'UnmodifiableUint8ListView'.
UnmodifiableUint8ListView(Uint8List(0));
```

**Comment by FauconSpartiate** [comment]
@Tom-ne run `flutter pub upgrade` in your terminal

**Comment by Tom-ne** [comment]
after running flutter upgrade in the latest version:

```
Launching lib/main.dart on Chrome in debug mode...
../../../.pub-cache/hosted/pub.dev/archive-3.4.9/lib/src/bzip2/bzip2.dart:5:7: Error: Method not found: 'UnmodifiableUint8ListView'.
      UnmodifiableUint8ListView(Uint8List(0));
      ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/archive-3.4.9/lib/src/bzip2/bzip2.dart:7:7: Error: Method not found: 'UnmodifiableUint32ListView'.
      UnmodifiableUint32ListView(Uint32List(0));
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/archive-3.4.9/lib/src/bzip2/bzip2.dart:9:7: Error: Method not found: 'UnmodifiableInt32ListView'.
      UnmodifiableInt32ListView(Int32List(0));
      ^^^^^^^^^^^^^^^^^^^^^^^^^
Failed to compile application.

Exited (1).

```

**Comment by alfatlaloc** [comment]
I've tried all fixed but none of them work, the problem is the archive version of this repo, that happens in the stable channel, pls merge this pr :( 🙏

**Comment by FauconSpartiate** [comment]
@justkawal

**Review by FauconSpartiate — APPROVED** [review]

**Comment by ViniciusSossela** [comment]
As a workaround:
```
dependency_overrides:
  archive: ^3.6.1
```

**Comment by jumacDev** [comment]
@justkawal

**Comment by alfatlaloc** [comment]
@justkawal we need you :(

**Review by justkawal — APPROVED** [review]

**Comment by justkawal** [comment]
Approved and published, I'm really really sorry for the delay....
Most of the time, I'm trying to up-skill and finding a tech-job as an immigrant....

I hope you all understand...., Sorry....

**Comment by alfatlaloc** [comment]
@justkawal thanks! if you need some hands you can tell us, i would like to contribute

**Pull request merged**
