### PR TITLE
Bump to 3.0.0

### PR DESCRIPTION
**Pull request by FauconSpartiate**
Bump package version to 3.0.0 and create changelog for that version.

The major version bump is due to the breaking changes from #245 and #254 to the API.

After #253, #254 and this PR get merged, everything can be PR'd to the publish branch for release.

### CODE REVIEW

**Comment by FauconSpartiate** [comment]
@justkawal Review needed

**Review by justkawal — DISMISSED** [review]
LGTM

**Comment by FauconSpartiate** [comment]
@justkawal Review needed again after solving merge conflicts

**Review by justkawal — APPROVED** [review]
LGTM

**Pull request merged**
