### PR TITLE
Support xml ^6.0.0

### LINKED ISSUE #179: xml version mismatch with auto_route_generator
Please update the xml version as the auto_route_generator also has a dependency on the xml package.

Capture

### PR DESCRIPTION
**Pull request by yutae**
## Support xml ^6.0.1

fix #179

[xml](https://pub.dev/packages/xml) was updated ago 6 months (^6.0.0)

### CODE REVIEW

**Comment by rshrc** [comment]
@justkawal can we merge this please?

**Review by justkawal — APPROVED** [review]
LGTM

**Comment by FauconSpartiate** [comment]
This is actually a bad idea to implement, as this will block any compatibility with version 5.0.0 from xml. This package actually works with it, ther is no need to constrain it to 6.0.0 and up...
Many conflict issues have been solved in version 2.0.1 that got released yesterday, so that issue is now also gone.

**Comment by justkawal** [comment]
> This is actually a bad idea to implement, as this will block any compatibility with version 5.0.0 from xml. This package actually works with it, ther is no need to constrain it to 6.0.0 and up...
> Many conflict issues have been solved in version 2.0.1 that got released yesterday, so that issue is now also gone.

Nice point.

**Pull request closed without merging**
