### PR TITLE
Implementation of range selection

### PR DESCRIPTION
**Pull request by ArinFaraj**
Added 4 methods to sheet class. to get cell data or the values in a specific range.
With the ability to get a range of data using the same method in excel i.e. `selectRangeWithString ('A1:D3')`

```dart
List<List<Data>> selectRangeWithString (String range)
List<List<Data>> selectRange (CellIndex start, {CellIndex end})
List<List<dynamic>> selectRangeValuesWithString (String range)
List<List<dynamic>> selectRangeValues (CellIndex start, {CellIndex end})
```

### CODE REVIEW

**Comment by ArinFaraj** [comment]
Had too much work, pushed this without testing but it has some bugs, I'll fix it and will let you know

**Comment by ArinFaraj** [comment]
It's now perfectly fine

**Comment by justraman** [comment]
Thank you @ArinFaraj  for your contribution. I'll update you on this once i have done with testing.

**Comment by justkawal** [comment]
> It's now perfectly fine

Good work mate, and thanks for pull request. 
Will be merged in few hours after testing completes

**Pull request merged**
