### PR TITLE
Merge publish into main

### PR DESCRIPTION
**Pull request by FauconSpartiate**
There are still some errors on merging, main and publish should be at the same commit level.

### CODE REVIEW

**Review by justkawal — APPROVED** [review]
LGTM

**Comment by justkawal** [comment]
The tests did passed but then it failed after merging @FauconSpartiate. Any idea buddy?

**Comment by FauconSpartiate** [comment]
Very weird, did I mess up the merge conflicts?
I'll look into it

**Comment by FauconSpartiate** [comment]
Looking at the logs, sometimes it doesn't find a file inside a temp folder? Rerunning it again worked...
Any issue with the test cases or the runner?

**Pull request merged**
